-- 리셋용
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS ARTICLE;
DROP TABLE IF EXISTS "USER";

-- 1. 유저 테이블 (USER는 예약어이므로 "USER"로 감싸야 합니다)
CREATE TABLE IF NOT EXISTS "USER" (
    userId VARCHAR(50) PRIMARY KEY,
    password VARCHAR(50) NOT NULL,
    name VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100),
    profileImage VARCHAR(255)
);

-- 2. 게시글 테이블
CREATE TABLE IF NOT EXISTS ARTICLE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    writer VARCHAR(50) NOT NULL,
    title VARCHAR(100),
    contents TEXT,
    imagePath VARCHAR(255),
    likeCount INT DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (writer) REFERENCES "USER"(userId) ON DELETE CASCADE
);

-- 3. 댓글 테이블
CREATE TABLE IF NOT EXISTS COMMENT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    articleId BIGINT NOT NULL,
    userId VARCHAR(50) NOT NULL,
    writerName VARCHAR(50) NOT NULL,
    contents TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (articleId) REFERENCES ARTICLE(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES "USER"(userId) ON DELETE CASCADE
);